### ISSUE TITLE
Highlighting breaks in type signatures

### ISSUE THREAD

**Issue by Fresheyeball** [atom-haskell/language-haskell#101]
![image](https://cloud.githubusercontent.com/assets/609279/22164090/e89d4e7e-df12-11e6-9b32-adaea8bdce43.png)

**Comment by lierdakil** [comment]
See https://github.com/atom-haskell/language-haskell/issues/57. TL;DR, until Atom offers another syntax model (tree-sitter? something else?) I can't do anything about this.

**Comment by moodmosaic** [comment]
Is `language-haskell` based on tree-sitter or just the old TextMate (.tmLanguage) format?

**Comment by lierdakil** [comment]
Still on TM model. There was a [project for tree-sitter grammar for Haskell](https://github.com/tree-sitter/tree-sitter-haskell), but it apparently stalled a while ago. TBH, language-haskell works "well enough" in most cases, and re-writing it ground-up for tree-sitter is obviously not something one could do in an evening or two.

Another point to consider, this grammar is used in the GitHub linguist project (i.e. for syntax highlighting on the site). AFAIK, linguist doesn't support tree-sitter grammars yet. Switching language-haskell to tree-sitter will kinda break Haskell highlighting on GitHub for a bit, which isn't ideal.

So realistically, language-haskell is likely to stay TM-based for the foreseeable future. That said, I'd be happy to support an alternative tree-sitter-based grammar, if someone's willing to work on that. I currently don't have the time to take on a project like this, regrettably, I have my hands somewhat full as it is. Even if I try, it'll likely just stall and die before resembling something production-ready.

**Comment by moodmosaic** [comment]
It's impressive how nicely it works! It's by far the more precise syntax highlighting for Haskell, compared at least with VSCode (worst of all) and Sublime Text (better than VSCode).

**Comment by moodmosaic** [comment]
@lierdakil, since a tree-sitter grammar for Haskell isn't happening, I guess it would be, theoretically, possible to convert the `.cson` files to `.tmLanguage`? This way they should be reusable outside Atom, e.g. TextMate, Code, Sublime Text, etcetera.

---

Apologies if I hijacked this thread. I'll be opening a new one depending on what @lierdakil answers.

**Comment by lierdakil** [comment]
> it would be, theoretically, possible to convert the .cson files to .tmLanguage

Theoretically, sure, should be relatively straightforward. Feel free to experiment. That said, I think I've seen some good tmLanguage Haskell grammars, e.g. see https://github.com/JustusAdam/language-haskell
