### ISSUE TITLE
Feature Request: special case for `undefined`

### ISSUE THREAD

**Issue by Fresheyeball** [atom-haskell/language-haskell#102]
I like to use `undefined :: forall a. a` in my workflow, it would be nice if I could custom style it to be angry and red.

**Comment by lierdakil** [comment]
Singling out `undefined` doesn't sound like a good idea. Why not `error` then as well? Both are basically `_|_`. And where there are two, there are all `Prelude` identifiers, which are already treated specially.

I will think about adding more specific scope descriptors to those, but I'm not sure it's a good idea.

**Comment by lierdakil** [comment]
v1.11.0 adds named scope to prelude identifiers. F.ex., `undefined` will be `support.function.prelude.undefined.haskell`. You can add styling you want in your stylesheet.
