### ISSUE TITLE
Feature request: .hsig grammar

### ISSUE THREAD

**Issue by chris-martin** [atom-haskell/language-haskell#107]
GHC recently added [module signatures](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/separate_compilation.html#module-signatures). These have a `.hsig` extension. It looks like their grammar is basically the same as a normal Haskell file, but with the keyword `signature` instead of `module`.

**Comment by lierdakil** [comment]
Published *something* as v1.13.0. If you could provide some somewhat real-world example `hsig` files, that would be nice.

**Comment by chris-martin** [comment]
Thanks. I think it's too early for there to really be *real-world* module signatures, but Ed Yang has a few nontrivial examples.

https://github.com/ezyang/reflex-backpack/blob/247898fde872d8909392ebe2539f4623c7449067/indef/Reflex/Sig.hsig
https://github.com/ezyang/reflex-backpack/blob/247898fde872d8909392ebe2539f4623c7449067/host/Reflex/Host/Sig.hsig
https://github.com/ezyang/backpack-regex-example/blob/2444a5084dcc6f82fcab9209e769fac86a426d79/regex-indef/Str.hsig

**Comment by lierdakil** [comment]
Thank you, that helps. I think I'm going to close this. If there are some problems with hsig syntax highlighting, feel free to open new issues.
