### ISSUE TITLE
Pragmas like LANGUAGE and INLINE are case insensitive in GHC, but recognized by github viewer only when uppercase.

### ISSUE THREAD

**Issue by ethercrow** [atom-haskell/language-haskell#109]
Example: https://github.com/yi-editor/yi-rope/blob/master/src/Yi/Rope.hs#L1

**Comment by lierdakil** [comment]
Thanks for reporting, fixed in v1.13.3. Might take a while before it makes it into GitHub's system though.

**Comment by ethercrow** [comment]
Thanks!
