### ISSUE TITLE
Qualified quasi quotes displayed incorrectly

### ISSUE THREAD

**Issue by tfausak** [atom-haskell/language-haskell#111]
![capture](https://user-images.githubusercontent.com/408753/31312230-343f69c4-ab83-11e7-8607-81288c6813f0.PNG)

This is with Atom 1.21.0 and language-haskell 1.14.2.

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in v1.14.3.

**Comment by tfausak** [comment]
Great, thanks for the quick turnaround!
