### ISSUE TITLE
The comment highlighting is broken by '=' for data

### ISSUE THREAD

**Issue by OlivierSohn** [atom-haskell/language-haskell#117]
![capture d ecran 2018-05-11 a 13 30 54](https://user-images.githubusercontent.com/8191319/39922612-22ff9304-5520-11e8-8c7a-6606c3b288fd.png)

Similar to #116 but a bit different. I'm testing with version 1.17.6

**Comment by lierdakil** [comment]
Thanks for the report! Should be fixed in v1.17.7
