### ISSUE TITLE
Explicitly exported infix constructor confuses the highlighter

### ISSUE THREAD

**Issue by leonschoorl** [atom-haskell/language-haskell#118]
While perfectly valid according to GHC, the following example looks wrong in Atom.
`myHead` and all subsequent exports are colored red.
```haskell
module MyList
  ( MyList(Nil,(:>))
  , myHead
  ) where

data MyList a = a :> MyList a | Nil
myHead (a :> _) = a
```

**Comment by lierdakil** [comment]
Thanks for your report! This is an unfortunate oversight that should be fixed in v1.17.8.

It will take some time for it to trickle down to GitHub's system though, but that also will happen eventually.
