### ISSUE TITLE
Pasting indented code

### ISSUE THREAD

**Issue by rogerbosman** [atom-haskell/language-haskell#119]
Hi guys,

I'm unsure if this is a configuration issue or even language-haskell's "fault", but I have a long-standing annoyance when pasting code.  Whenever I paste code, it pastes everything at the indentation the next line is expected, instead of the cursor line.

Example:

```
toBeCopied = helper
  where
    helper = somefun

instance Eq ...
  x == y = ...

|
```

Lets say we cut-and-paste the toBeCopied example at the cursor indicated by |. You expect to get it aligned normally, but instead you get:

```
instance Eq ...
  x == y = ...

  toBeCopied = helper
    where
      helper = somefun
```

Any way to correct for this?

**Comment by lierdakil** [comment]
Hi. Sorry for the belated response.

Long story short, Atom's auto-indentation model is, well, not very flexible, and doesn't really work all that well with languages with significant indentation. It is especially awful when pasting code. I will admit though that language-haskell might not have the best indentation rules either, but I don't have a very good idea of how and what to fix exactly, tbh.

Anyway, the way to "fix" (or more "work around") this particular deficiency is to disable Atom's "indent on paste" feature. Go to Settings → Editor and disable the option.

![image](https://user-images.githubusercontent.com/7275622/54195179-14d60480-44cf-11e9-9a3c-272c58f94d6d.png)

You can also disable it for Haskell specifically by editing config by hand.

```cson
"source.haskell":
  editor:
    autoIndentOnPaste: false
```
