### ISSUE TITLE
Existential quantification support

### ISSUE THREAD

**Issue by MatthijsBlom** [atom-haskell/language-haskell#124]
I just noticed this:

![existquant](https://user-images.githubusercontent.com/19817960/62086540-ed55bd80-b25e-11e9-8937-2421b5c5f7d9.png)

It seems existential quantification is not supported.

I have not yet looked into how this may have come to pass. Perhaps I will do so tomorrow.

**Comment by lierdakil** [comment]
Fixed in v1.19.1. Pretty sure this worked at _some_ point, but was broken along the way and nobody really noticed until now, and there was no regression test for this.

Thanks for reporting!
