### ISSUE TITLE
Highlighting broken in export list after exporting an infix type constructor with explicit list of constructors

### ISSUE THREAD

**Issue by Lysxia** [atom-haskell/language-haskell#125]
```haskell
module Test
  ( (:-)(), apply
  ) where
```

Picture for posterity's sake:

![sc-2019-11-16T18:20:17-05:00](https://user-images.githubusercontent.com/2515201/69000456-e8645a80-089d-11ea-81ce-b7b741c616b7.png)

**Comment by lierdakil** [comment]
Thanks for reporting!

I've published a new release, but it will take a little while (usually a couple weeks) until it makes its way into GitHub's system.

**Comment by Lysxia** [comment]
Thanks a lot!
