### ISSUE TITLE
Deriving via type constructor with Symbol argument

### ISSUE THREAD

**Issue by akrmn** [atom-haskell/language-haskell#126]
Syntax highlighting breaks when the first argument to the via-type is a `Symbol` starting with an upper case letter. Notably, this doesn't happen when the `Symbol` starts with a lower case letter, nor when the entire via-type is inside parens. Since this is valid Haskell code, the highlighter shouldn't break.

![image](https://user-images.githubusercontent.com/6054733/73359860-11dc3200-42a2-11ea-940c-8824a29dcacb.png)

**Comment by lierdakil** [comment]
Hi. Thanks for your report.

The thing that breaks syntax highlighting here is actually double quotes, which is easy enough to fix. 

Highlighting the `via` syntax like in your example is another matter. The limited grammar engine doesn't allow us to match this syntax entirely correctly. I've made some adjustments for common cases where `via` is on the same line as its argument, as in your example, and for the case where `via` is the first non-whitespace thing on the line, e.g.
```
newtype Foo a = Foo (Bar a)
    deriving Something
          via
            Bar "Quux" Baz
```
Note however, that we have to require indentation on the continuation line, that is, this will not work:
```
newtype Foo a = Foo (Bar a)
    deriving Something
          via
          Bar "Quux" Baz
```

Anyway, version 1.19.3 should be live now, see if it works for you.

**Comment by akrmn** [comment]
Hey, thanks a lot for the quick response! It works as expected now.
