### ISSUE TITLE
Can we port this to Sublime Text and/or VSCode syntax?

### ISSUE THREAD

**Issue by moodmosaic** [atom-haskell/language-haskell#130]
This package probably has the most accurate Haskell syntax grammar out there.

Since we all know that Atom [will be archived on December 15, 2022](https://github.blog/2022-06-08-sunsetting-atom/). I was wondering if we can, perhaps, target this to Sublime Text and/or VSCode?

---

I ❤️ Atom (and Sublime Text!) by the way. Just wondering, is all.

**Comment by lierdakil** [comment]
Yeah... I jumped ship to VS Code myself a while back, so this is considered unmaintained. This uses Atom's TextMate style grammar definitions, so it should be relatively straightforward to generate TextMate compatible grammar out of this. I'm wondering however if it would be better to improve [@JustusAdam's grammar](https://github.com/JustusAdam/language-haskell) with stuff from here as to avoid fragmenting the ecosystem. Do you haver particular examples where this here grammar does a better job than @JustusAdam's one?

**Comment by moodmosaic** [comment]
Sure. A good example is [haskell-hedgehog/hedgehog/src/Hedgehog/Internal/Tree.hs](https://github.com/hedgehogqa/haskell-hedgehog/blob/c47d867d54eb1a6c34be744dcff42593b33e038a/hedgehog/src/Hedgehog/Internal/Tree.hs).

Here are some screenshots I took, having Atom (language-haskell) and Code (justusadam.language-haskell) side-by-side:

![image](https://user-images.githubusercontent.com/287532/190681432-081a1bc4-f984-4a20-9e0a-d1860757ef6a.png)

![image](https://user-images.githubusercontent.com/287532/190681486-fbe0b5f0-d4fe-49e9-b4b0-1ed30a502a43.png)

![image](https://user-images.githubusercontent.com/287532/190681528-7ce1b47f-55a5-47d0-a5b1-2e5ebbb8cfcf.png)

**Comment by moodmosaic** [comment]
The Atom one feels more accurate and more detailed, in my opinion.

**Comment by lierdakil** [comment]
So... For one, I believe your syntax theme doesn't support all scopes provided by `justusadam.language-haskell`. Try groovy lambda. Or just add some scope rules to `settings.json`, e.g. here's what I have (I use one dark pro theme):

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "comment.block.documentation.haskell",
                "settings": {
                    "foreground": "#ddddaa"
                }
            },
            {
                "scope": "comment.line.double-dash.haskell",
                "settings": {
                    "foreground": "#aaaacc"
                }
            },
            {
                "scope": "entity.name.namespace.haskell",
                "settings": {
                    "foreground": "#C0A077"
                }
            },
            {
                "scope": "keyword.operator.function.infix.haskell",
                "settings": {
                    "foreground": "#CC77AC"
                }
            },
            {
                "scope": "keyword.operator.infix.haskell",
                "settings": {
                    "foreground": "#CF8C00"
                }
            },
            {
                "scope": "constant.other.haskell",
                "settings": {
                    "foreground": "#e06c75"
                }
            },
            {
                "scope": "variable.other.member.haskell",
                "settings": {
                    "foreground": "#cbb2bf"
                }
            }
        ]
    },
```

It can get pretty close, in my experience

![image](https://user-images.githubusercontent.com/7275622/190844801-676a7b0e-1537-4ca7-9d03-162009b2886b.png)
![image](https://user-images.githubusercontent.com/7275622/190844821-ca7e4666-e046-4906-8598-1868bec3514b.png)
![image](https://user-images.githubusercontent.com/7275622/190844832-e7a3c709-74dd-4073-ac21-2ff57466e2e3.png)

**Comment by lierdakil** [comment]
The two things I do notice are `Prelude` identifiers and C preprocessor directives. The former I'm not convinced is particularly useful, and it took a bit of effort to maintain; I think it should be possible to cook up an injection grammar doing it though, which on paper seems like a more sustainable option. The latter should be relatively straightforward to add, at least to the same standard as language-haskell does it (which is to say, highlight the first word after `#` as keyword)

**Comment by moodmosaic** [comment]
>I believe your syntax theme doesn't support all scopes

Yes, I should have mentioned that in both cases (Atom, Code) I'm using the default/built-in themes for doing the comparison.

>I use one dark pro theme

Which one? I can see at least two:
1. [Binaryify/OneDark-Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) (6M installs)
2. [AdrianWilczynski/OneDarkPro](https://marketplace.visualstudio.com/items?itemName=adrianwilczynski.one-dark-pro) (250K installs)

**Edit**: Just realized that the `2.` is for Visual Studio, so then I guess you're using `1.` which is for Visual Studio Code.

**Comment by lierdakil** [comment]
Yep, https://github.com/Binaryify/OneDark-Pro

**Comment by moodmosaic** [comment]
And just to be sure... when you said
>try groovy lambda

you mean https://github.com/sheaf/groovy-lambda

**Comment by lierdakil** [comment]
Indeed. That's the one liked from [JustusAdam/language-haskell](https://github.com/JustusAdam/language-haskell) readme. Supposedly it's one of the few themes making the full use of the scopes defined by the grammar (but it's too low-contrast for my taste).

**Comment by moodmosaic** [comment]
Groovy Lambda compared with https://github.com/atom-haskell/language-haskell/issues/130#issuecomment-1249537628 is actually pretty accurate 👀 

Those scope rules in https://github.com/atom-haskell/language-haskell/issues/130#issuecomment-1250019962 are also good (not that accurate/complete, compared to what seems to come built-in with Groovy Lamda, but we can always extend them). 👍 

---

I think I'll close this, then. Because even if we port this syntax into Visual Studio Code (TextMate), we'd also have to port/use/suggest an appropriate theme (as JustusAdam/language-haskell does with Groovy Lamda).

However, if I port this into Sublime Text, I will leave a note here.
