### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by lierdakil** [atom-haskell/language-haskell#15]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/home/livid/bin/atom-dir/share/atom/resources/app/src/package.js:539:9)
<unknown> (/home/livid/bin/atom-dir/share/atom/resources/app/src/package.js:188:43)
```

This is only shown in dev-mode, thought I might as well give a heads-up.

**Comment by nwolverson** [comment]
Such duplication #17 #18 #20 #22 #24
