### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by bobo1995** [atom-haskell/language-haskell#27]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:586:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:43)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
```

**Comment by chriskrycho** [comment]
Thanks for maintaining this. What's the ETA for shipping an update that include #28? It's getting awfully close to Atom 1.0 time…

**Comment by impinball** [comment]
[It's going to be removed June 1st, roughly a month before then.](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html)

**Comment by impinball** [comment]
Please version-bump this.
