### ISSUE TITLE
Syntax Highlighting has changed

### ISSUE THREAD

**Issue by Axmill** [atom-haskell/language-haskell#36]
The syntax highlighting has changed very much, and I do not think it was intended.
![screenshot 2015-06-16 00 31 13](https://cloud.githubusercontent.com/assets/4473843/8175840/152c66f8-13bf-11e5-88ba-d157ddc1f27a.png)

**Comment by lierdakil** [comment]
Thanks for reporting.

First line is my mistake. I'll fix that shortly. Sorry.

I'm not sure I understand what line 6 is supposed to represent, although I could probably fix word anchoring on type names.

As for the rest, `Just` and other prelude type constructors are marked as `support.tag.haskell`. In general, type constructors are marked as `tag`s, either `support.tag.haskell` for prelude, or `entity.name.tag.haskell` for other. Same goes for type signature: prelude classes are marked as `support.class.prelude.haskell`, while other types are `entity.name.type.haskell`.

If you point me to highlighting theme you're using, I might think of a way to make it work better, either with a pull request, or by adding/changing scope descriptors.

**Comment by lierdakil** [comment]
This is what it looks like with `one-dark-syntax` theme
![image](https://cloud.githubusercontent.com/assets/7275622/8176523/827b04cc-1404-11e5-8fc0-57796f2a0e80.png)

YMMV depending on highlighting theme.

**Comment by Axmill** [comment]
I think it might just be that my theme (Monokai) highlights those as plain text.

Sorry for being late to reply.
