### ISSUE TITLE
Recognize quasiquoters

### ISSUE THREAD

**Issue by 3noch** [atom-haskell/language-haskell#37]
It looks like this package does not realize that a quasi-quoter is being used, and so it treats the contents and the subsequent code without properly recognizing the presence of the quasi-quoter. Considering the boundless variability of quasi-quoter behavior, perhaps the best thing to do is just treat anything within a quasiquote as its own thing (with an appropriate styling).

![image](https://cloud.githubusercontent.com/assets/882455/8435249/480189f4-1f1e-11e5-974e-53526123d4bf.png)

**Comment by lierdakil** [comment]
Thanks for reporting. Can't give you an ETA, but I'll try to fix this soon.

**Comment by lierdakil** [comment]
I've added support for quasiqotes, it was easier than I imagined. Bear in mind that quasiquotes are not easy to distinguish from list comprehensions, at least not with Atom's grammar parsing rules. So list comprehensions like this `[ x | x <- codelisting, not $ useListings opts]` *have* to have spaces either after `[` or before `|` or both.
Somehow I suspect I will have a couple bug reports about that soon...

**Comment by 3noch** [comment]
Wow, I never realized that syntactical ambiguity. How does GHC handle that?

**Comment by 3noch** [comment]
I suppose with the ending token `|]`, but it sounds like Atom's grammar parsing rules aren't helpful for that.

**Comment by lierdakil** [comment]
No idea, but I would assume it searches for quasiquote closing `|]`, and if it doesn't find it, assumes comprehension. Sadly, with Atom's grammar parsing rules (copied from TextMate) can't do that.
