### ISSUE TITLE
Auto-indentation problem

### ISSUE THREAD

**Issue by edsko** [atom-haskell/language-haskell#40]
(I'm not entirely sure `language-haskell` is to blame for this, but) whenever I press enter the cursor is one space to the left or where it is supposed to be. I.e., if I am

```
     -- some comment
                    ^ cursor here
```

and then press enter it ends up

```
     -- some comment

    ^ cursor here
```

rather than

```
     -- some comment

     ^ cursor here
```

This didn't use to happen.

Weirdly, when I press enter on a blank line, it does go to the right location.

(PS. I have my tab-size set to 1, for reasons I explain in [my blog post](http://www.edsko.net/2015/03/07/vim-to-atom/) about switching to Atom. I wonder if that's related.)

**Comment by lierdakil** [comment]
Couldn't reproduce here with tab size 1 or 2. If auto-indent is on, cursor is placed correctly, regardless of actual indentation (i.e. if it's indented by one space, new line is also indented by one space). If it's off, cursor is placed at the beginning of line (that's expected).

So either you'll have to investigate this yourself, or provide an isolated test-case with detailed description of your setup. Sorry I can't be of more help.

**Comment by stevecheckoway** [comment]
This happens for me as well with a new install of Atom. I've installed 4 packages: haskell-ghc-mod, ide-haskell, language-haskell, and autocomplete-haskell. With language-haskell enabled and the others disabled, indentation is one level less than it should be (in my case, 2 spaces). With language-haskell disabled, indentation is correct. This happens in every .hs file.

I'm using Atom 1.0.2 on OS X 10.10.4 I'm happy to provide any additional information you wish.

**Comment by lierdakil** [comment]
One thing I can think of is `increaseIndentPattern' and `decreaseIndentPattern` going awry for some reason. Technically, that would be a bug in Atom, but let's see if I'm right.

Open `~/.atom/packages/language-haskell/settings/language-haskell.cson` and remove these lines:
```cson
    'increaseIndentPattern': '((^.*(=|\\bdo|\\bwhere|\\bthen|\\belse|\\bof)\\s*$)|(^.*\\bif(?!.*\\bthen\\b.*\\belse\\b.*).*$))'
    'decreaseIndentPattern': '^\\s*$'
```

Restart Atom, then check if this still happens. Also try to determine if it's former or latter, if possible (by removing one line and leaving another in).

Thanks.

**Comment by edsko** [comment]
@lierdakil Just tried that and that does indeed fix it:

Both enabled: broken
Both disabled: works
Only first enabled: works
Only second enabled: broken

**Comment by lierdakil** [comment]
Well, this was lifted directly from TexMate Haskell bundle, and now it's apparently broken for some reason. For now, I'll remove `decreaseIndentPattern`, since I don't think it works as expected on any platform anyway. Should talk with upstream though, since this shouldn't be a problem.

**Comment by lierdakil** [comment]
Note: I also fixed `increaseIndentPattern`, which apparently also stopped working, at least for me. If you don't like this indentation settings, see README for customization options.

**Comment by lierdakil** [comment]
Update: this was apparently fixed upstream with https://github.com/atom/atom/pull/7858. Should be in Atom v1.0.3 when it gets released. I will try to add `decreaseIndentPattern` back when it is. I assume this can be closed.

**Comment by svanharmelen** [comment]
@lierdakil can we talk on IRC or gitter somewhere? Have some more info about this one I would like to share...

**Comment by lierdakil** [comment]
@svanharmelen you can drop by at https://gitter.im/atom-haskell/ide-haskell, but I can't say I have too much time on my hands atm, so real-time chat is not very likely.

**Comment by maxbrunsfeld** [comment]
I don't think the indentation pattern in the haskell TextMate bundle is correct. In [this commit](https://github.com/textmate/haskell.tmbundle/commit/59cfe4d29c0cee9201c86d32861e0fdd6459e8ad), the authors of that bundle explicitly *disabled* indentation correction (whatever that means).

**Comment by maxbrunsfeld** [comment]
Actually, maybe using TextMate's `disableIndentCorrections` key is similar to using Atom's new `decreaseNextIndentPattern` setting instead of `decreaseIndentPattern`: it prevents the matching line from being outdented while your cursor is on it.

**Comment by edsko** [comment]
Do you know if this can be overridden locally, without modifying the Haskell file? The bracketing behaviour was still driving me nuts:

![autoindent](https://cloud.githubusercontent.com/assets/935288/11466991/7357bde0-9745-11e5-89f0-148d21721fc2.gif)

Removing the definition of `increaseIndentPattern` from `~/.atom/packages/language-haskell/settings/language-haskell.cson` then seemed restore the default behaviour, which moved the bracket to the start of the previous line. I want to position my brackets manually (I know I'm weird :) so I now defined

```
    'increaseIndentPattern': ''
    'decreaseIndentPattern': ''
```

and that seems to have done the trick.

**Comment by lierdakil** [comment]
@edsko https://github.com/atom-haskell/language-haskell#auto-indent ?

**Comment by edsko** [comment]
Haha, oops, RTFM edsko :) Thanks! :)
