### ISSUE TITLE
Bird track specs

### ISSUE THREAD

**Issue by zenzike** [atom-haskell/language-haskell#41]
The literate haskell grammar correctly works with bird tracks that start with `>`, which are equivalent to `\begin{code} ... \end{code}` blocks.

However, the tracks that are for specifications, `<`, that correspond to `\begin{spec} ... \end{spec}` do not work.

**Comment by lierdakil** [comment]
Added support for those in 1.1.9. Sorry about the holdup, I was (and honestly, still am) insanely busy lately.

**Comment by zenzike** [comment]
Wonderful: a big thank you!
