### ISSUE TITLE
Commented out inline code

### ISSUE THREAD

**Issue by zenzike** [atom-haskell/language-haskell#45]
When using literate Haskell, it is common for authors to use lhs2TeX. Text is treated as comments by default. In this context, inline references to code are usually made between `|` symbols, for instance, we might discuss the type of `id` and write `|id :: a -> a|`. Currently the syntax highlighting for such quoted code does not work as expected (it's not unhighlighted, but it's not treated as Haskell code either).

**Comment by lierdakil** [comment]
Literate Haskell grammar treats all text, that is not code (i.e. outside of bird track/code/spec block), as TeX/LaTeX. So it is within reason that `|...|` is not recognized as special syntax. Not sure I understand what you mean by "unhighlighted" there. Could you provide a screenshot of incorrect highlighting maybe?..

**Comment by zenzike** [comment]
I see, that makes sense. This first screenshot shows the behaviour in atom:
![image](https://cloud.githubusercontent.com/assets/161292/9281447/151d5f96-42bd-11e5-8556-5455c9fa5343.png)
The second screenshot shows the expected behaviour, as demonstrated in vim:
![image](https://cloud.githubusercontent.com/assets/161292/9281459/2630d74a-42bd-11e5-9d52-727b418f277f.png)
Notice that in vim the text between the pipes gets highlighted as if it were Haskell code. Looking at the language definition in Vim, we have:

    syntax region lhsHaskellInline keepend start="\%(\\verb\)\@<!|" end="|" contains=@haskellTop,@NoSpell containedin=@lhsTeXNoVerb

Essentially this says that text inside pipes that isn't part of a latex `\verb| ... |` should be treated as Haskell. This would be nice in atom too!

**Comment by zenzike** [comment]
I can confirm that what I meant by "not unhighlighted" is that text within pipes is highlighted as if it were in latex, where there seem to be some special rules too. In an lhs file, I think it's right to assume it's Haskell.

**Comment by lierdakil** [comment]
Added some limited support. Please note that not all syntax highlighting in `|` escapes will be correct, f.ex. type signatures are guaranteed to be messed up (since regular Haskell grammar doesn't allow those to hang mid-line). Also, due to Atom's syntax model, hanging pipes (i.e. opening pipe without closing one) will mess up syntax highlighting completely. Let me know if this creates problems, I might try to alleviate it somewhat.
