### ISSUE TITLE
Highlighting - long strings with type declaration

### ISSUE THREAD

**Issue by ryachza** [atom-haskell/language-haskell#47]
I have been experiencing an issue that when combining type declarations and long strings (more than 94 characters), the highlighting seems to ignore the closing quotation.

    module Main where

    test :: String
    test = "aaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbb"

    main = return ()

When opening the above sample, the `main = ...` (and anything further, if added) appears highlighted as though it is part of the string.

This no longer happens when performing any of:
* Removing one character from the string
* Removing the `test :: String` type declaration
* Moving the closing quotation to (or adding a quotation on) a line below the string

**Comment by lierdakil** [comment]
Thanks for reporting. Sorry it took so long to get to this.

Initial investigation seems to suggest it's a bug in Atom. That said, I've worked around it somewhat, so 1.4.2 should be relatively good (there still are some minor quirks with this, but your particular complaint should be resolved).

**Comment by lierdakil** [comment]
Should be fixed in 1.7.1
