### ISSUE TITLE
add note about color schemes etc. please

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/language-haskell#48]
The screen shot here looks very good. How did you get that? What color scheme is that? What other packages / settings achieved that look? It's better than what I've otherwise achieved. Thanks

**Comment by lierdakil** [comment]
Sceenshot was taken with 'One Dark' Atom theme (syntax and UI), with DejaVu Sans Mono font, on Linux, if it matters at all. I think it's just that.

**Comment by wolftune** [comment]
Thanks. I'm playing around… I like One Dark's colors, but how come it fails to highlight certain arrows and other symbols that solarized dark finds? Sorry for my naive questions, I'm new to much of this. I find it baffling that I simply want to maximize the differentiation shown for semantically different markings but still choose overall colors I like. Why do different color schemes bring out different sets of distinctions?

Solarized:
![solarized](https://cloud.githubusercontent.com/assets/2801853/9798107/b7191226-57b3-11e5-8543-ab1ddb0572d2.png)

One-Dark:
![one-dark](https://cloud.githubusercontent.com/assets/2801853/9798112/c48da44e-57b3-11e5-8485-f5f3feedc94e.png)

**Comment by lierdakil** [comment]
One dark doesn't seem to define special highlighting color for operators. You can define your own, however, by adding something like this to your stylesheet (Edit → Your Stylesheet):
```less
atom-text-editor::shadow {
  .source.haskell {
    .keyword.operator {
      color: red;
    }
  }
}
```

Note that special subclass is defined for infix notation (`.operator.infix`).

Also consider starting type specifications on new line, otherwise those are impossible to find with regex. E.g.
```haskell
let
  migration_files :: [(Int, String)]
  migration_files = …
```

**Comment by wolftune** [comment]
thanks! So would it make sense to post a ticket to other color schemes saying "add a special color for operators" ?

**Comment by lierdakil** [comment]
I guess it would. `.keyword.operator` is quite standard.
