### ISSUE TITLE
special highlight for parentheses and brackets?

### ISSUE THREAD

**Issue by wolftune** [atom-haskell/language-haskell#49]
As far as I can tell (though things seems to vary depending on color scheme chosen), there's no highlighting distinction for parentheses and brackets etc.

**Comment by lierdakil** [comment]
Let's just say it's more effort than I'd like to put into something like this and leave it at that, shall we? There are entities defined for unit `()` and empty list `[]`. Parentheses and brackets are treated as plain text in other cases. Those can have a *very* different meaning depending on context, and grammar is already bloated beyond reason.

**Comment by wolftune** [comment]
Okay, thanks for the reply
