### ISSUE TITLE
Parse error on escaped backslash "\\"

### ISSUE THREAD

**Issue by munro** [atom-haskell/language-haskell#53]
Escaped backslashes wreaking havoc in code, and eyes 😵

![image](https://cloud.githubusercontent.com/assets/500774/10038119/049d343a-6175-11e5-80c0-7cc11dcfb24a.png)

**Comment by munro** [comment]
nvm!  I see it's fixed on master

**Comment by lierdakil** [comment]
Um. No, it's not. Should be fixed with 1.4.7, however.
