### ISSUE TITLE
Problems with multi-line type signatures

### ISSUE THREAD

**Issue by rhwlo** [atom-haskell/language-haskell#57]
I have a tendency to write multi-line type signatures, e.g.:

```
square :: Num a
       => a
       -> a
```

and it looks like `language-haskell` only matches the type constraint `Num a` as a constraint if it’s on the same line as the `=>`. I looked at fixing this but unfortunately I don’t have a very good understanding of the Atom grammar, and it seems like multi-line matching might get tricky.

Any thoughts?

**Comment by lierdakil** [comment]
Problem is, Atom's grammar model parses source file line-by-line. Based on just

```haskell
square :: Num a
```

it doesn't have enough information to decide if it's a class constraint, or a return type. And backtracking is not allowed.

So all in all, I can only support syntax where `=>` is on the same line as class constraint itself, unless I reimplement grammar parser from scratch (not an easy task, and not something I have time for, at least for now)

**Comment by rhwlo** [comment]
I was wondering if this was the case! I knew that Atom parsed line-by-line like Textmate does, but I hadn’t connected that this made distinguishing between a one-line and multi-line type signature impossible. That’s too bad! Do you think it’s worth bringing this up as an issue to the developers of Atom itself?

**Comment by lierdakil** [comment]
Well, might be worth a shot, but I don't think that would accomplish much.

Somewhat relevant issues:
https://github.com/atom/first-mate/issues/50
https://github.com/atom/atom/issues/8669
https://github.com/atom/first-mate/issues/34

**Comment by rhwlo** [comment]
Thanks for the help :smile:
