### ISSUE TITLE
Function type declaration with newline between name and "::" is not highlighted correctly.

### ISSUE THREAD

**Issue by Keyholder** [atom-haskell/language-haskell#59]
This is highlighted:

    whenJust :: Applicative m => Maybe a -> (a -> m ()) -> m ()

This is not:

    whenJust
        :: Applicative m
        => Maybe a -> (a -> m ()) -> m ()

**Comment by lierdakil** [comment]
Sorry, I missed notification somehow.

Long story short, this is *impossible* to highlight with Atom's syntax model, since it parses one line at a time and backtracking is not allowed. Maybe in a distant future, if we get a better syntax model...

**Comment by Keyholder** [comment]
Aww... That's sad and unfortunate!

**Comment by lierdakil** [comment]
I have to agree. Still, this problem isn't exclusive to Atom -- many editors suffer from relatively poor syntax models, sadly.
