### ISSUE TITLE
Module export constructors over multiple lines

### ISSUE THREAD

**Issue by codebje** [atom-haskell/language-haskell#60]
The following code makes module export highlighting go wonky for the multi-line constructor list and all following exports:

```{haskell}
module Fine.Module
    ( AnExport (ExportKind1, ExportKind2)
    , ABigSumType ( SumBranch1
                  , SumBranch2
                  , SumBranch3
                  , SumBranch4)
    , nowShownIncorrectly ) where
```

GitHub's syntax highlighter doesn't like this, either.

**Comment by lierdakil** [comment]
v1.5.1 should be fine. Thanks for reporting.
