### ISSUE TITLE
language-haskell fails to install

### ISSUE THREAD

**Issue by Blindsniper** [atom-haskell/language-haskell#61]
I'm getting an error trying to install language-haskell for atom run as sudo with the output

    
> language-haskell@1.5.1 postinstall /tmp/apm-install-dir-1151121-5681-g8m2sv/node_modules/language-haskell
> coffee src/haskell.coffee

/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:127
      throw err;
            ^
Error: EACCES, permission denied '/tmp/apm-install-dir-1151121-5681-g8m2sv/node_modules/language-haskell/src/haskell.coffee'
  at Object.fs.statSync (fs.js:696:18)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:120:18)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3

npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/thomas/.atom/.apm/.apmrc" "--userconfig" "/home/thomas/.atom/.apmrc" "install" "/tmp/d-1151121-5681-1dke0u6/package.tgz" "--target=0.34.3" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! language-haskell@1.5.1 postinstall: `coffee src/haskell.coffee`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the language-haskell@1.5.1 postinstall script 'coffee src/haskell.coffee'.
npm ERR! This is most likely a problem with the language-haskell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee src/haskell.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls language-haskell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1151121-5681-g8m2sv/npm-debug.log

**Comment by lierdakil** [comment]
It seems like either a permissions error, or your node installation being broken?.. You really *shouldn't* run apm with sudo though. Or Atom for that matter.

**Comment by jacowley** [comment]
I'm also getting an error when trying to install this package in atom. Unfortunately the npm-debug.log file doesn't exist at the path given:
```
Installing “language-haskell@1.5.2” failed.Hide output…

> language-haskell@1.5.2 postinstall /private/var/folders/sz/4dm2gs_14mg3b50zl5_pyrgr0000gn/T/apm-install-dir-116115-17397-vjmwk6/node_modules/language-haskell
> coffee src/haskell.coffee


npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jcowley/.atom/.apm/.apmrc" "--userconfig" "/Users/jcowley/.atom/.apmrc" "install" "/private/var/folders/sz/4dm2gs_14mg3b50zl5_pyrgr0000gn/T/d-116115-17397-jyk00u/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! language-haskell@1.5.2 postinstall: `coffee src/haskell.coffee`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the language-haskell@1.5.2 postinstall script 'coffee src/haskell.coffee'.
npm ERR! This is most likely a problem with the language-haskell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee src/haskell.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls language-haskell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/sz/4dm2gs_14mg3b50zl5_pyrgr0000gn/T/apm-install-dir-116115-17397-vjmwk6/npm-debug.log
```

**Comment by lierdakil** [comment]
@jacowley, this is a wild guess, but you might try to `npm install coffee-script`. I'm not entirely sure why it fails to find binary in its own dependencies though.

**Comment by jacowley** [comment]
@lierdakil Thanks for the suggestion but that didn't work. I managed to fix the problem by re-installing Atom.
