### ISSUE TITLE
Symbolic snippets don't allow completion

### ISSUE THREAD

**Issue by cblp** [atom-haskell/language-haskell#62]
When I type `mo` or `im` I see module or import snippet.
But when I type `{` or `>`, nothing happens.
They present in snippet list (Snippets: Available), but are not triggered automatically.
And even when I use the Pragma snippet from the list, it inserts only `{-#  #-`, so I assume it definitely is not the proper way to insert this snippet.
So how to use it properly? Or is it broken?

**Comment by lierdakil** [comment]
Sorry about the delay.

Snippets are "activated" on `Tab` keypress. Those are also shown in autocomplete dialog.

For example:

```
imp<tab>
```

will expand to

```haskell
import Module
````

etc.

`{-# #-` is like this because Atom automatically inserts `}` when you input `{`. `{-#<tab>` will then become `{-# #-}` because of that.

**Comment by cblp** [comment]
The problem is that Pragma snipper is NOT activated on Tab.

**Comment by lierdakil** [comment]
Works for me:

![pragma-snippet](https://cloud.githubusercontent.com/assets/7275622/13555310/4b22798e-e3ce-11e5-8fb0-80e41b581629.gif)

**Comment by lierdakil** [comment]
This is done via `snippets:expand` command. See if it's bound to `tab`, and make sure it's not overridden with another command (you can use keybinding resolver: `key-binding-resolver:toggle` -- bound to `ctrl+.` by default)

**Comment by cblp** [comment]
Okay, I was wrong a little. The way with Tab works. But only this way. You have to type full snippet prefix. This way doesn't save significant amount of key strokes.

With other snippets, when you start typing prefix, a competion list appears. With Pragma and other symbolic snippets it doesn't. That's the problem.

**Comment by cblp** [comment]
> Those are also shown in autocomplete dialog.

I don't see neither `Pragma` nor `{-#` in the completion dialog.

**Comment by lierdakil** [comment]
Well, that's the problem with autocomplete-plus, since it doesn't understand symbolic prefixes. I can't do much about that on my end.  See e.g. https://github.com/atom/autocomplete-snippets/issues/56 https://github.com/atom/autocomplete-snippets/issues/67

**Comment by cblp** [comment]
Thank you for help.
