### ISSUE TITLE
Inline code with :: breaks syntax highlighting in literate Haskell

### ISSUE THREAD

**Issue by scmu** [atom-haskell/language-haskell#64]
Inline code with (::) breaks syntax highlighting in literate Haskell. See the following screen capture. Notice that the text after f :: a -> a are wrongly highlighted as code: 

![screen shot 2016-03-16 at 11 04 45 am](https://cloud.githubusercontent.com/assets/11384501/13800733/f1a65d58-eb66-11e5-90a2-59a9dab95006.jpg)

and see the same text with (::) removed

![screen shot 2016-03-16 at 11 04 54 am](https://cloud.githubusercontent.com/assets/11384501/13800736/f5fcdad0-eb66-11e5-8daf-8bf7819c7d02.jpg)

language-haskell version 1.7.3.
haskell-ghc-mod version 1.11.2.
ide-haskell disabled.

**Comment by lierdakil** [comment]
Thank you for reporting

**Comment by scmu** [comment]
Seems that this problem has come back in language-haskell 1.9.7. See screen shot:

![screen shot 2016-09-14 at 10 03 45 pm](https://cloud.githubusercontent.com/assets/11384501/18515229/3189aea8-7ac7-11e6-8bcf-7fab3e234c0c.jpg)

**Comment by lierdakil** [comment]
Sorry about that. 1.9.8 should be fine. I've added a regression test to keep this from happening... frankly, I think this is a deficiency in grammar model, since there is no way of preventing an inner scope from escaping, but that's something we'll have to live with for now.

**Comment by scmu** [comment]
Thank you! 

Yet another tiny bug, however: in the last line in the example below, Atom seems to parse "|." as an operator. It only happens when it appears after a "::".

![screen shot 2016-09-15 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/11384501/18539197/f3600772-7b47-11e6-8195-d238efd23dfb.jpg)

Thank you for fixing all these! I agree that it is a deficiency in the grammar. We unfortunately have to come up with very ad-hoc solutions... :(

**Comment by lierdakil** [comment]
should finally be fixed, although it sacrifices some flexibility.

Code like this `|map :: (a -> b) -> [a] -> [b]|`, etc should work correctly.

As well as code like this: `|[(x :: Int) || x <- []]|`. Note that lhs2TeX requires
you use double pipe `||` in inline code where you would normally use one.

However, breaking lines in inline code doesn't work anymore, e.g.
```
| let a =
123 |
```
vs `| let a = 123 |`.

This is mostly a limitation of grammar parser. I believe this is a reasonable
tradeoff.

![image](https://cloud.githubusercontent.com/assets/7275622/18554060/af2a05a2-7b6b-11e6-9bf2-7e7de32fd7b5.png)
