### ISSUE TITLE
Atom stops responding trying to open haskell files

### ISSUE THREAD

**Issue by mdibaiee** [atom-haskell/language-haskell#66]
After updating `language-haskell` (I think there were a few updates, haven't had used ide-haskell for around a week), when I try to open Haskell files, Atom just hangs and asks Keep Waiting or Close.

I tried getting a log from Atom using atom --log-file but it just doesn't seem to work, no file is written, maybe the editor hangs before any logs pop, although that's not what I think.

```
atom@1.6.1
language-haskell@1.7.7
```

**Comment by lierdakil** [comment]
If you could give an example of file that causes this issue, that would be nice.

**Comment by lierdakil** [comment]
Probably catastrophic backtracking in parser.

**Comment by mdibaiee** [comment]
Ah, it seems I was wrong, it's not about `language-haskell` itself, it's caused by `haskell-ghc-mod` alone. If I disable all my haskell-related packages and only enable `haskell-ghc-mod`, Atom stops responding, that means it's not about `ide-haskell` or `autocomplete-haskell` which depend on it.

Sorry about the messed up issues on different repositories. Should I fill another issue in `haskell-ghc-mod`?

Thanks.

**Comment by lierdakil** [comment]
Nevermind that. First, what version of ghc-mod do you use? Second, could you see if disabling `stackSandbox` option helps?

**Comment by mdibaiee** [comment]
ghc-mod version 5.5.0.0 compiled by GHC 7.10.3

Yes, disabling `stackSandbox` works! :+1:

**Comment by lierdakil** [comment]
This is probably due to stack running `stack setup` on first call. Since I have to call `stack path` synchronously to get path to sandbox, it hangs everything. I was under impression that stack does *not* run `setup` on `path`, however. Oh well. I've added a timeout to `stack path` call (configurable via haskell-ghc-mod settings). This isn't really a solution, but at least editor won't hang anymore.

**Comment by mdibaiee** [comment]
@lierdakil yup, the timeout seems to work around the problem, thank you!

I think it was because I had run `stack init` and interrupted it (never let it finish), not sure how relevant that might be though.
