### ISSUE TITLE
Critical bug - language-haskell freezes atom when opening some files.

### ISSUE THREAD

**Issue by wdanilo** [atom-haskell/language-haskell#68]
Hello!
I've been using `language-haskell` and `ide-haskell` for some time now and I've noticed that when I open some source files language-haskell makes atom to use 100% of CPU and hangs forever. I'm sure that this is caused by this package, because I disabled everything else and the problem still occurs (after disabling `language-haskell` the file opens as it should). I paste the content of an example file causing the error below:

```
{-# LANGUAGE DeriveDataTypeable   #-}
{-# LANGUAGE EmptyDataDecls       #-}
{-# LANGUAGE TypeFamilies         #-}
{-# LANGUAGE TypeOperators        #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE PolyKinds            #-}
{-# LANGUAGE ScopedTypeVariables            #-}

module Type.List where

import Data.Typeable
import Prelude
import GHC.Exts (Constraint)
import GHC.TypeLits
import Type.Bool
import Type.Container
import qualified Type.Set as Set

-- === Wrappers ===

data Lst (l :: [k])

type family FromLst a where FromLst (Lst l) = l

-- === Basic operations ===

type family Removed    (el :: e)    (cont :: c) :: l
type family RemovedIdx (idx :: Nat) (cont :: c) :: l
type family ElAt       (idx :: Nat) (cont :: c) :: l

type instance Removed (el :: e) ((l ': ls) :: [e]) = If (el == l) ls (l ': Removed el ls)


type instance RemovedIdx idx (l ': ls) = If (idx == 0) ls (l ': RemovedIdx (idx - 1) ls)

type instance ElAt idx (l ': ls) = If (idx == 0) l (ElAt (idx - 1) ls)


type instance In a (l ': ls) = If (a == l) True (In a ls)
type instance In a '[]       = False


type family SuccMaybe (m :: Maybe Nat) where SuccMaybe (Just n) = Just (n + 1)
                                             SuccMaybe Nothing  = Nothing

type instance Index a (l ': ls) = If (a == l) (Just 0) (SuccMaybe (Index a ls))
type instance Index a '[]       = (Nothing :: Maybe Nat)


data Recursive a

type instance Index a (Recursive (l ': ls)) = If (a == l) (Just 0) (SuccMaybe (Index a (Recursive ls)))
type instance Index a (Recursive '[]      ) = (Nothing :: Maybe Nat)


--type family Index2 (idx :: i) (cont :: c) :: el

type instance Index2 n (a ': as) = If (n == 0) a (Index2 (n - 1) as)


type instance Empty '[]       = 'True
type instance Empty (a ': as) = 'False


type instance Append a '[]       = '[a]
type instance Append a (l ': ls) = l ': Append a ls


type instance Concat ('[] :: [k])        (lst :: [k]) = lst
type instance Concat ( (l ': ls) :: [k]) (lst :: [k]) = l ': Concat ls lst


type instance Remove a '[] = '[]
type instance Remove a (l ': ls) = If (a == l) ls (l ': Remove a ls)


type instance Diff l '[]       = l
type instance Diff l (e ': es) = Diff (Remove e l) es

type instance Size '[]       = 0
type instance Size (a ': as) = 1 + Size as

type family Head lst where
    Head '[]       = 'Nothing
    Head (a ': as) = 'Just a

type family Head' lst where Head' (a ': as) = a

--type instance Unique (lst :: [k]) = Set.ToList (Set.AsSet lst)

-- FIXME[WD]: The following is just an fix for using Unique.
--            Due to lack of time this ugly fix has no background - probably some PolyKinded problem.
type family UniqueFix lst where UniqueFix '[] = '[]
                                UniqueFix lst = Unique lst
type instance Unique (lst :: [k]) = Set.ToList (Set.AsSet lst)

type instance Reverse (lst :: [k]) = Reverse' lst '[]

type family Reverse' lst lst' where
    Reverse' '[]       lst = lst
    Reverse' (l ': ls) lst = Reverse' ls (l ': lst)


type family Take (n :: Nat) lst where
    Take 0 lst       = '[]
    Take n (l ': ls) = l ': Take (n - 1) ls

type family Drop (n :: Nat) lst where
    Drop 0 lst       = lst
    Drop n (l ': ls) = Drop (n - 1) ls

--type instance Index (a :: *) (Recursive ((l ': ls) ::  [*] )) = If (a == l) (Just 0) (SuccMaybe (Index a (Recursive ls)))
--type instance Index (a :: *) (Recursive ((l ': ls) :: [[*]])) = If (Index a l == 'Nothing) (SuccMaybe (Index a (Recursive ls))) ('Just 0)
--type instance Index a '[]                                     = 'Nothing


--type instance RecIndex a ((l ': ls) :: [[*]]) = If (RecIndex a l == 'Nothing) (SuccMaybe (RecIndex a ls)) (Just 0)



type family Last (lst :: [k]) :: k where
    Last '[x]      = x
    Last (x ': xs) = Last xs


type family Init (lst :: [k]) :: [k] where
    Init '[]       = '[]
    Init '[x]      = '[]
    Init (x ': xs) = x ': Init xs

type family DropInit (lst :: [k]) :: [k] where
    DropInit '[]       = '[]
    DropInit '[x]      = '[x]
    DropInit (x ': xs) = DropInit xs

type family Replicate (n :: Nat) a where
    Replicate 0 a = '[]
    Replicate n a = a ': Replicate (n - 1) a


type Zip a b = Zip2 a b

type family Zip2 (l1 :: [*]) (l2 :: [*]) :: [*] where
    Zip2 (x1 ': xs1) (x2 ': xs2) = (x1,x2) ': Zip2 xs1 xs2
    Zip2 l1          l2          = '[]

type family Zip3 (l1 :: [*]) (l2 :: [*]) (l3 :: [*]) :: [*] where
    Zip3 (x1 ': xs1) (x2 ': xs2) (x3 ': xs3) = (x1,x2,x3) ': Zip3 xs1 xs2 xs3
    Zip3 l1          l2          l3          = '[]

type family Zip4 (l1 :: [*]) (l2 :: [*]) (l3 :: [*]) (l4 :: [*]) :: [*] where
    Zip4 (x1 ': xs1) (x2 ': xs2) (x3 ': xs3) (x4 ': xs4) = (x1,x2,x3,x4) ': Zip4 xs1 xs2 xs3 xs4
    Zip4 l1          l2          l3          l4          = '[]

type family Zip5 (l1 :: [*]) (l2 :: [*]) (l3 :: [*]) (l4 :: [*]) (l5 :: [*]) :: [*] where
    Zip5 (x1 ': xs1) (x2 ': xs2) (x3 ': xs3) (x4 ': xs4) (x5 ': xs5) = (x1,x2,x3,x4,x5) ': Zip5 xs1 xs2 xs3 xs4 xs5
    Zip5 l1          l2          l3          l4          l5          = '[]


type family Unzip2 (lst :: [*]) :: ([*], [*]) where
    Unzip2 '[]              = '( '[], '[] )
    Unzip2 ((x1,x2) ': lst) = PrependAll (x1,x2) (Unzip2 lst)

--type family Unzip3 (lst :: [*]) :: ([*], [*], [*]) where
--    Unzip3 '[]              = '( '[], '[] )
--    Unzip3 ((x1,x2) ': lst) = PrependAll (x1,x2) (Unzip3 lst)


type family PrependAll (els :: *) (lsts :: k) :: k
type instance PrependAll (t1,t2) '(l1,l2) = '(t1 ': l1, t2 ': l2)
type instance PrependAll (t1,t2,t3) '(l1,l2,l3) = '(t1 ': l1, t2 ': l2, t3 ': l3)
type instance PrependAll (t1,t2,t3,t4) '(l1,l2,l3,l4) = '(t1 ': l1, t2 ': l2, t3 ': l3, t4 ': l4)
type instance PrependAll (t1,t2,t3,t4,t5) '(l1,l2,l3,l4,l5) = '(t1 ': l1, t2 ': l2, t3 ': l3, t4 ': l4, t5 ': l5)


type family Select (n :: Nat) (a :: *) :: *

type instance Select 1 (t1,t2) = t1
type instance Select 2 (t1,t2) = t2

type instance Select 1 (t1,t2,t3) = t1
type instance Select 2 (t1,t2,t3) = t2
type instance Select 3 (t1,t2,t3) = t3

type instance Select 1 (t1,t2,t3,t4) = t1
type instance Select 2 (t1,t2,t3,t4) = t2
type instance Select 3 (t1,t2,t3,t4) = t3
type instance Select 4 (t1,t2,t3,t4) = t4

type instance Select 1 (t1,t2,t3,t4,t5) = t1
type instance Select 2 (t1,t2,t3,t4,t5) = t2
type instance Select 3 (t1,t2,t3,t4,t5) = t3
type instance Select 4 (t1,t2,t3,t4,t5) = t4
type instance Select 5 (t1,t2,t3,t4,t5) = t5



type family Update (n :: Nat) (a :: k) (lst :: [k]) :: [k] where
    Update 0 a (l ': ls) = a ': ls
    Update n a (l ': ls) = l ': Update (n - 1) a ls
```

**Comment by wdanilo** [comment]
O, some further information - it seems that parsing is hanging forever - If i comment everything, then I can notice the following things:

1) when uncommenting line `Zip4 l1          l2          l3          l4          = '[]` the parsing takes about 2-3 s
2) when uncommenting line `Zip5 l1          l2          l3          l4          l5          = '[]` it just hangs

**Comment by lierdakil** [comment]
Thanks for reporting. Somewhat fixed in v1.7.9. Type family highlighting can leave a lot to be desired though. Feel free to open new issues if you have suggestions.

**Comment by wdanilo** [comment]
Thanks for fixing it so fast. Yep that true - the TF highlighting is really bad here. What suggestions are you looking for? I would love to have better highliting here and I can try to help if you need something specific :)

**Comment by lierdakil** [comment]
I'm not too familiar with type families. So, for one I'm not sure if it makes more sense to treat types in a closed type family as type declarations or constructor definitions (highlighting-wise). In any case, if you see something that isn't highlighted properly in your opinion (or at all), you can open an issue and we'll see what can be done.

**Comment by wdanilo** [comment]
Ok, so think about type families just like about functions on type level, which names start with an uppercase letter. Thats all. In GHC 8 this is more than true. In fact the whole code I've pasted above is just wrongly highlighted - If you want to see proper highlighting, paste it in Sublime, it does much better job with TF's, though I think it is much simplier than what you are doing here. Can I provide to you any further info regarding TFs? (look at the definitions I've pasted and think about TF's like about just functions - no matter if its closed or not - the closed type families are the same as open with slightly different matching rules).

**Comment by wdanilo** [comment]
Additional - would it be possible to just highlight each word starting with uppercase like sublime does? It would be much better than now, because now a lot o lines in my code ar just white, like for example: `instance Castable (Unwrapped (Layer t l)) (Unwrapped (Layer t' l')) => Castable (Layer t l) (Layer t' l') where`, where sublime colorizes it just based on the starting letter being capital or not and it works pretty ok.

**Comment by lierdakil** [comment]
Um. I think you might want to change/extend your syntax theme there.

language-haskell tries to differentiate type *names* and type *constructors*, since those two have very different semantic meaning in most cases. So type names and type constructors have different scopes.

Type names (usually found in type declarations and signatures) have `entity.name.type.haskell` scope.
Type constructors (usually found elsewhere) have `entity.name.tag.haskell` scope.

F.ex.
![image](https://cloud.githubusercontent.com/assets/7275622/14330633/15161eb0-fc4a-11e5-9c63-201c584698f2.png)

There are also separate scopes for prelude types (`support.class.prelude.haskell`) and type variables (`variable.other.generic-type.haskell`).

Here's a snippet you can paste into your stylesheet (Edit → Stylesheet...) to see some of those:

```less
atom-text-editor::shadow {
  .entity.name.tag.haskell {
    color: red;
  }
  .entity.name.type.haskell {
    color: yellow;
  }
  .support.class.prelude.haskell {
    color: lime;
  }
}
```

(yes, these colors will burn your retinas, but at least are hard to miss)

**Comment by wdanilo** [comment]
Oh that's so cool! I didnt know we can affect the colors so easy in Atom! I knew we've got stylesheets but didnt know I can so easy access the scopes given by the "lexer". Where can I find all possible "names", like `.entity.name.type.haskell` ?

**Comment by lierdakil** [comment]
The most straightforward way is to look at https://github.com/atom-haskell/language-haskell/blob/master/src/haskell.coffee 

That said, you can see what scopes are currently under cursor by running 'Editor: Log Cursor Scope' command from command palette (I think it's `ctrl`+`alt`+`shift`+`P` by default). Last one in list is usually one you want to override style for.

**Comment by lierdakil** [comment]
I tried to stick to common conventions when naming those scopes (for the sake of theme compatibility, but you see how that turned out). So some names can make less sense than others.

**Comment by wdanilo** [comment]
Ok, thank you for providing so great info! I'll definitely will try to mess with it to see what can we improve here. One thing that I'm constantly thinking about for the last 15 minutes is your sentence: `language-haskell tries to differentiate type names and type constructors, since those two have very different semantic meaning in most cases`. It's not true in most cases... From my experience - it is impossible to differentiate those two things (unless you are using ghc-mod or something like that to provide you the info). For example - how do you treat type aliases? While parsing you don't know if they are aliases for constructors or other type families. The same applies to type families, because they can be just aliases for constructors. I understand that we can make here some guessing, but sometimes it gives strange results, like this one (all the names have exactly the same meaning - they are the same type-level-function name):

![screen shot 2016-04-06 at 22 51 47](https://cloud.githubusercontent.com/assets/1623053/14332514/38158b4e-fc4a-11e5-842d-7c5a308c6b3c.png)

**Comment by lierdakil** [comment]
Well, that's the reason I was asking about closed type families.

From my experience, there is a limited number of contexts in which type names make sense. Of course there are some border cases, but I'm willing to trade some weirdness for more semantically-aware markup.

**Comment by lierdakil** [comment]
You might be pleased to learn that I finally got around to fixing highlighting for type/data families. Feel free to open new issues if something's not right. Thanks for your patience.
