### ISSUE TITLE
Leading hash tags were recognized as start of comment where shouldn't

### ISSUE THREAD

**Issue by zakyggaps** [atom-haskell/language-haskell#70]
In certain packages `#` is defined as a flipped version of `$` and very likely to appear at the beginning of lines, but currently it will render the whole line, occasionally several lines as comment (or not, the color is slightly different from a comment), cancel nearly any other syntax highlight by the way.

Here is an example:

    infixr 0 #
    (#) :: a -> (a -> b) -> b
    (#) = flip ($)

    -- line case
    application :: Int
    application = 1
      # (one + two)
      # (+)
      where
        one = 1
        two = 2

    -- multi-line case
    application' :: Int
    application' = 1
      # (one' + two)
      # (+)
      where
        one' = 1
        two  = 2

**Comment by lierdakil** [comment]
Note that 

```haskell
#something
```

will still be parsed as C++, since it's not really viable to toggle this behavior based on language pragmas (besides, CPP might be enabled elsewhere)
