### ISSUE TITLE
[Feature request] support ScopedTypeVariables syntax highlighting

### ISSUE THREAD

**Issue by cblp** [atom-haskell/language-haskell#71]
![_005](https://cloud.githubusercontent.com/assets/63495/14817754/3101f60a-0bca-11e6-9d74-531be905367e.png)

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

main = do
    x <- readLn                   -- ok
    x :: String <- readLn         -- BAD COLORING
    (x :: String) <- readLn       -- ok

    let r = readLn                -- ok
        r :: IO String = readLn   -- BAD COLORING
        (r :: IO String) = readLn -- ok
    let r :: IO String = readLn   -- ok
    let (r :: IO String) = readLn -- ok
```

**Comment by lierdakil** [comment]
It's impossible to differentiate between

```haskell
type_annotation :: SomeType
```

and

```haskell
scoped_type :: OtherType
              = undefined
```

without backtracking (something Atom's grammar model cannot do)

```haskell
scoped_type :: OtherType = undefined
```
is marginally better in this regard

In all honesty, I'm tempted to advise you to parenthesize scoped type declarations. Those should work unconditionally.

**Comment by lierdakil** [comment]
v1.9.2 should alleviate this somewhat. I strongly suggest using parentheses though
