### ISSUE TITLE
apostrophe should not cause identifier to be highlighted differently

### ISSUE THREAD

**Issue by bouzlibop** [atom-haskell/language-haskell#72]
Here is  an example:

<img width="341" alt="screen shot 2016-05-01 at 16 06 09" src="https://cloud.githubusercontent.com/assets/8625570/14942235/d80d67c8-0fb6-11e6-8d3b-1e2c768360b9.png">

I think the whole word `conanO'Brien` should have the same color as `'` is a valid character in functions.

**Comment by lierdakil** [comment]
This should work as expected now. Problem was identifiers weren't tokenized at all, so `Brien` part was captured as a type constructor.

A side effect is that qualified identifiers (e.g. `Data.Maybe.fromMaybe`) now tokenize 'module' part as `support.other.module.haskell`. You might want to adjust stylesheet accordingly.

**Comment by bouzlibop** [comment]
thanks! 😄
