### ISSUE TITLE
I cannot install "language-haskell" plug-in anymore on Windows 10

### ISSUE THREAD

**Issue by varosi** [atom-haskell/language-haskell#73]
On installation of 1.7.13 on Windows 10 x64

Currently it is giving error:
> 'coffee' is not recognized as an internal or external command,
> operable program or batch file.

I tried reinstalling whole Atom application and deletion of C:\Users\Home\.atom\
But nothing helps. I don't know if anything else is missing. I don't have errors on Atom installation.

**Comment by lierdakil** [comment]
Try 1.7.14. Maybe it will work.

**Comment by varosi** [comment]
How to install previous version? Currently in Atom I see only 1.7.15 as an option.

**Comment by lierdakil** [comment]
Don't worry about it. Does 1.7.15 work for you?

**Comment by varosi** [comment]
Nope, but error is different:

> Installing “language-haskell@1.7.15” failed.Hide output…
> 
> > language-haskell@1.7.15 postinstall C:\Users\Vassil\AppData\Local\Temp\apm-install-dir-11644-8588-pdq2e2\node_modules\language-haskell
> > node ./node_modules/coffee-script/bin/coffee src/haskell.coffee
> 
> 
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: Cloning into 'C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383'...
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: git-upload-pack 'C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e': git-upload-pack: command not found
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: fatal: Could not read from remote repository.
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: 
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: Please make sure you have the correct access rights
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: and the repository exists.
> npm ERR! git clone C:\Users\Vassil\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\Vassil\AppData\Local\Temp\npm-12940-078c85ec\git-cache-d423bb698dc2\73fd7202ac086c26f18c9d56f025b18b3c6f5383: 
> npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
> 'node' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\Vassil\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Vassil\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Vassil\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Vassil\\.atom\\.apmrc" "install" "C:\\Users\\Vassil\\AppData\\Local\\Temp\\d-11644-8588-1gdj3zn\\package.tgz" "--target=0.36.8" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! language-haskell@1.7.15 postinstall: `node ./node_modules/coffee-script/bin/coffee src/haskell.coffee`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the language-haskell@1.7.15 postinstall script 'node ./node_modules/coffee-script/bin/coffee src/haskell.coffee'.
> npm ERR! This is most likely a problem with the language-haskell package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./node_modules/coffee-script/bin/coffee src/haskell.coffee
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls language-haskell
> npm ERR! There is likely additional logging output above.

**Comment by varosi** [comment]
I see wrong paths, like:
C:\Users\Vassil.atom.apm_git-remotes\...
it should be:
C:\Users\Vassil\.atom\.apm...

**Comment by lierdakil** [comment]
Okay, so I have literally no idea what's wrong with your system, but I just recently had a report (#74) that 1.7.15 installs fine on Windows NT 6.2.9200...

Things to try:
- Try installing via cmdline with `apm install language-haskell`
- Try cloning repository directly, then run `apm install; apm link` in cloned root

There are other options, if all else fails, but this is highly perplexing.

**Comment by varosi** [comment]
"apm install language-haskell" gave the same issue with missing "node".

2016-05-04 23:26 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by varosi** [comment]
clone + "apm install" gave the same message with missing "node" on PATH.

2016-05-05 21:36 GMT+03:00 eng. Vassil Ognyanov Keremidchiev <
varosi@gmail.com>:

**Comment by varosi** [comment]
I don't have "node.exe" on my PATH. Is it comming with Atom itself?

**Comment by varosi** [comment]
hm, adding "%USERPROFILE%\AppData\Local\atom\app-1.7.3\resources\app\apm\bin" to my PATH explicitly solved the problem. But shouldn't that happen automatically on language-haskell installation?

**Comment by lierdakil** [comment]
It should. And generally, it does. I have no idea why this fails for you.
5 мая 2016 г. 9:44 PM пользователь "varosi" <notifications@github.com>
написал:

**Comment by varosi** [comment]
What can I do to help you find source of the problem?

2016-05-05 23:47 GMT+03:00 Nikolay Yakimov <notifications@github.com>:

**Comment by lierdakil** [comment]
Only thing I can think of is take a dummy package with postinstall hook containing `env > /env-dump.txt` and see what environment does apm *actually* run in. Then we probably can backtrack from there.

Here's a barebones `package.json`:

```json
{
  "name": "dummy",
  "version": "0.0.1",
  "license": "MIT",
  "engines": {
    "atom": ">=0.174.0 <2.0.0"
  },
  "scripts": {
    "postinstall": "env > /env-dump.txt; false"
  }
}
```

Note that postinstall hook is designed to fail.

P.S. I'm not actually sure what shell does nodejs use on Windows, so this might fail to produce `/env-dump.txt`. If this is the case, try replacing `env` with `set`.

**Comment by varosi** [comment]
Happened on 1.7.17, too:
Updating to “language-haskell@1.7.17” failed.Hide output…

> > language-haskell@1.7.17 postinstall C:\Users\varosi\AppData\Local\Temp\apm-install-dir-116515-736632-1ch7qh5\node_modules\language-haskell
> > node ./node_modules/coffee-script/bin/coffee src/haskell.coffee
> 
> 
> npm ERR! git clone C:\Users\varosi\.atom\.apm\_git-remotes\git-github-com-michaelficarra-cscodegen-git-79ca3b9e C:\Users\varosi\AppData\Local\Temp\npm-727196-9cf4c6f2\git-cache-4a90d9ea02de\73fd7202ac086c26f18c9d56f025b18b3c6f5383: Cloning into 'C:\Users\varosi\AppData\Local\Temp\npm-727196-9cf4c6f2\git-cache-4a90d9ea02de\73fd7202ac086c26f18c9d56f025b18b3c6f5383'...

**Comment by varosi** [comment]
I don't know how to create Atom packages, but created folder:

> C:\Users\varosi\.atom\packages\dummy\

there I created file package.json with content you provided.

What to test with it?

**Comment by varosi** [comment]
Just clicked update to 1.7.17 and it worked fine. I don't know what have fixed the problem...
