### ISSUE TITLE
Disable Snippets?

### ISSUE THREAD

**Issue by WiWa** [atom-haskell/language-haskell#75]
I don't like coding with nonstandard characters and I don't see an option to uncheck.

**Comment by lierdakil** [comment]
Snippets are handled by `snippets` and `autocomplete-snippets` packages. Those don't have any configuration options, but if you don't use snippets at all, you might consider disabling one or both of those.

Other than that, you can directly remove snippets you don't use from package source. Bear in mind those will be overwritten on next update though.

**Comment by WiWa** [comment]
This is very odd. All I've installed is `language-haskell`, but when I press `tab` after typing `::` it autocorrects to unicode double colon.

**Comment by lierdakil** [comment]
Snippets themselves are defined in `language-haskell`. There has been requests for unicode syntax support, so I added those. *Actual tab substitution* is handled by `snippets` package. Which is in Atom core (i.e. installed by default). Snippets are also used by autocomplete-plus (also in core), via `autocomplete-snippets` (also in core).

Does it make sense now?

**Comment by WiWa** [comment]
The gods are good!
