### ISSUE TITLE
Syntax lighting bug after "*" in inline code.

### ISSUE THREAD

**Issue by scmu** [atom-haskell/language-haskell#76]
Text trailing inline code are wrongly highlighted as code, if the incode ends with a "*" without a space. See the attached screen shot. (language-haskell version 1.7.15).

![screen shot 2016-05-29 at 12 57 20 pm](https://cloud.githubusercontent.com/assets/11384501/15631430/f9060466-259c-11e6-95e8-452ad433cff2.jpg)

**Comment by lierdakil** [comment]
Why this happens: `*|` is interpreted as an operator, hence `|` is not parsed as inline code end.

Fix is rather awkward. I'm pushing it in hopes for the best.
