### ISSUE TITLE
'pure' keyword is not highlighted

### ISSUE THREAD

**Issue by ThatKorean** [atom-haskell/language-haskell#77]
Is there any reasoning for this? I think it is as important as `return` keyword. 
It looks now:
![selection_018](https://cloud.githubusercontent.com/assets/16170478/15884737/db912196-2d52-11e6-83b2-cba2131da14c.png)

**Comment by lierdakil** [comment]
`pure` is not exported from `Prelude`. `return` is. That's the reasoning.

**Comment by ThatKorean** [comment]
Isn't Monad an instance of Applicative since 7.10? I think it could be good reason to highlight it

**Comment by lierdakil** [comment]
Okay, updated.
