### ISSUE TITLE
Consider tracking generated grammars in repository

### ISSUE THREAD

**Issue by Alhadis** [atom-haskell/language-haskell#80]
Is there a reason the CSON grammars are only being generated *after* the package install?

It'd be great to use this package to provide Haskell highlighting on GitHub. However, in order to arrange that, we need static grammar files available in the repository.

I ask because there're issues with the site's current Haskell highlighting:

```haskell
-- Highlighted as comment
class X y
-- Not highlighted correctly
```

Yours, on the other hand, [highlights this correctly](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2FAlhadis%2F8b688311aeb8f92361ae010500c5482c%2Fraw%2F2d6cd9a1ab9d3aad6737f084091e7b90bfddb8cd%2Fhaskell.cson&grammar_text=&code_source=from-text&code_url=&code=--+Highlighted+as+comment%0D%0Aclass+X+y%0D%0A--+Not+highlighted+correctly).

GitHub currently uses the [original TextMate grammar](https://github.com/textmate/haskell.tmbundle) for highlighting, which doesn't get updated very often, and has numerous syntax issues. It'd be lovely to have highlighting controlled by a more active and maintained project. =)

**Comment by lierdakil** [comment]
> Is there a reason the CSON grammars are only being generated after the package install?

Only reason I did that is pull requests were sent to generated grammar instead of generator itself (which wasn't much fun, let me tell you). It's been causing some problems lately though, so I was contemplating switching back.

I should warn you though that type/data family highlighting is somewhat broken at the moment (well, at least it doesn't run away with infinite loops as it did before). I've been meaning to get to it one of these days, but other stuff kept me busy.

**Comment by Alhadis** [comment]
Well, you can alleviate the first issue by adding a PR template for GitHub to remind users their changes need to be done inside the source.

What's happening with the family highlighting?

**Comment by lierdakil** [comment]
Long story short, highlighting for type families is wrong semantically and is a bit messy overall. It's not breaking anything else. Still probably better than Github's default highlighting though

**Comment by Alhadis** [comment]
`s/probably/very clearly/`

You're curating this grammar very thoroughly and have probably fixed half the bugs that still exist in the original grammar. I'd say it's a much more qualified candidate for providing Haskell highlighting on GitHub. :)

**Comment by Alhadis** [comment]
* `/\bprobably\b/

(Sorry, I write language grammars too. I can't stand seeing a potentially flaky pattern)

**Comment by lierdakil** [comment]
Okay, pushed compiled grammars into repo. Have fun.

**Comment by Alhadis** [comment]
<img src="https://cloud.githubusercontent.com/assets/2346707/17463670/560e8022-5d0e-11e6-9775-f216d234302d.png" width="468" alt="yea" />
