### ISSUE TITLE
Nested block comments

### ISSUE THREAD

**Issue by RuralSpaceman** [atom-haskell/language-haskell#82]
Block comments in Haskell nest, but text after the first ```-}``` is formatted as code -- eg
```
{-
add1 x = x+1 {- inner comment -}
This line is still part of a block comment, but is formatted as code.
-}
```
I like to use ```{- -}``` to comment-out blocks of code when refactoring (perhaps I shouldn't?), and frequently, all indication that the code is inactive is offscreen.  (This bites me most often when commenting-out code that includes pragmas.)

**Comment by lierdakil** [comment]
This doesn't seem to be an issue with Atom 1.8.0. What Atom version are you using?

**Comment by lierdakil** [comment]
Looks fine to me on Atom 1.9.6 as well.

Try updating Atom. Also please check that you're actually using a grammar provided by `language-haskell` package and not, f.ex. `haskell-grammar`

**Comment by RuralSpaceman** [comment]
I was on 1.8, now on 1.9.8: same result.  I've disabled all Haskell-related packages except language-haskell, again with no change.

From your comments, it looks like I must be doing something wrong, but I can't see what.  Hopefully the attached screenshots will give a clue.

![screenshot_20160815_124145](https://cloud.githubusercontent.com/assets/18375312/17663622/c42faaa4-62e5-11e6-83c5-5f9706032bcf.png)

![screenshot_20160815_122549](https://cloud.githubusercontent.com/assets/18375312/17663316/b2a38686-62e3-11e6-9e7c-f44bd83fef96.png)

**Comment by lierdakil** [comment]
Okay, so I tested the code that you've shown in OP, and it works fine. Pragmas, however, mess this up. Sorry about misleading comments, but you didn't communicate what the problem was very well.

So I think I know why, and I will try to push a new version that should fix this shortly.

**Comment by RuralSpaceman** [comment]
Yes, just checked: my original code sample works for me too, now. (I thought it was misbehaving previously, but maybe I'm wrong and I only saw the misbehaviour with pragmas: in which case, apologies for miscommunicating.)

Thanks for the quick response.

**Comment by lierdakil** [comment]
Okay, 1.9.4 released with a fix for this issue :tada:. If you're interested, this bug is actually inheritance from textmate grammar, which is also used by github currently:

```haskell
{- comment {-# pragma #-} comment continued -}
```

And this happens basically because parser didn't match `{-#` as nested block comment start, but matched `#-}` as block comment end.

Out of performance concerns, now pragmas inside block comments are treated as nested block comments. Hopefully this isn't a problem for you.

Thanks for reporting!

**Comment by RuralSpaceman** [comment]
And just like that, I'm running the fixed version.  :tada: indeed!

>Out of performance concerns, now pragmas inside block comments are treated as nested block comments. Hopefully this isn't a problem for you.

I can't see that being an issue.

Thanks for fixing!
