### ISSUE TITLE
Bug in comment operations?

### ISSUE THREAD

**Issue by ggirotto** [atom-haskell/language-haskell#86]
After writing something in this form:
x=[a|

everything befor the pipe (|) becomes comments, dont know why

<img width="702" alt="screen shot 2016-09-02 at 22 50 45" src="https://cloud.githubusercontent.com/assets/11745745/18221990/c56fcf06-715f-11e6-9041-63d6ada72f5b.png">

**Comment by lierdakil** [comment]
Please see: https://github.com/atom-haskell/language-haskell/issues/37#issuecomment-117340844

**Comment by lierdakil** [comment]
Also http://ghc.readthedocs.io/en/8.0.1/glasgow_exts.html#quasi-quotes-list-comprehension-ambiguity, i.e. this is not a language-haskell specific problem, as that comment speculates.

**Comment by ggirotto** [comment]
Thank you, sorry abou that 👍
