### ISSUE TITLE
"class" and "data" are not highlighted as other keywords

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/language-haskell#87]
Atom Light theme:

![screenshot from 2016-09-12 18-10-49](https://cloud.githubusercontent.com/assets/873919/18441082/a4a0d44a-791c-11e6-9aca-be41de2d6150.png)

I expect `class` and `data` to be looked the same as `where`, `instance` and `deriving`.

**Comment by lierdakil** [comment]
Works fine for me:
![image](https://cloud.githubusercontent.com/assets/7275622/18528491/ed97e330-7ad1-11e6-9c6d-7270d38c4f02.png)

Most syntax themes handle this fine. I could add a `keyword` scope to class/type/data, but I'm not entirely sure about that. Some discussion is in order...

Summary of the problem: data/type/newtype/class use `storage.type` scope, as is customary in some other grammars for structs/classes/etc. This is not strictly correct for Haskell, esp. for `class`, although `data`/`type`/`newtype` actually *do* describe storage type. On the other hand, those are in fact keywords, so might as well label them as such.

/cc @Alhadis, @atom-haskell

**Comment by Alhadis** [comment]
For cases like this, I've found it beneficial to include `keyword` alongside the `storage` scope, even if it's not 100% semantically correct. Themes are more likely to add distinctive highlighting for keywords, and some don't even acknowledge the `storage` scope at all.

Also, sometimes I wish the `storage.` scope would stop existing.

**Comment by lierdakil** [comment]
I think anyone who wanted to say something on the issue, already did so. Ultimately I opted to change `storage.type` to `keyword.other`, since `storage.type` doesn't really make that much sense for Haskell -- it's not like there are C-style qualifiers like `static` or `volatile`. Hopefully it doesn't come back to haunt my dreams later.
