### ISSUE TITLE
:: on a new line highlights incorrectly

### ISSUE THREAD

**Issue by quchen** [atom-haskell/language-haskell#89]
Consider

```haskell
someValue
    :: (A -> B) 
    -> C

someValue
    :: Constraint 
    => (A -> B) 
    -> C
```

This style is common when Haddock-documenting the individual arguments of a function. The outcome is

![selection_003](https://cloud.githubusercontent.com/assets/3020161/18579662/60532012-7bf7-11e6-949b-ca35b31d5464.png)

where the type signature is detected to end prematurely (scope: `language.haskell` and nothing else).

The behaviour on deleting the newline before the `::` is equivalent from the language’s point of view, and handled correctly:

![selection_004](https://cloud.githubusercontent.com/assets/3020161/18579722/b02d20f6-7bf7-11e6-847a-dd3d880cd0f8.png)

**Comment by lierdakil** [comment]
This is expected. Atom's grammar model forbids backtracking and tokenizes
one line at a time, which means no lookahead. So there is absolutely no way
to figure out what a single identifier on a line means. Grammar falls back
to basically doing nothing in this case.

16 сент. 2016 г. 11:24 ДП пользователь "David Luposchainsky" <
notifications@github.com> написал:

**Comment by quchen** [comment]
Oh, that is unfortunate. Thanks anyway!
