### ISSUE TITLE
Types are highlighted differently in same expression

### ISSUE THREAD

**Issue by vasily-kirichenko** [atom-haskell/language-haskell#90]
![screenshot from 2016-09-18 11-33-35](https://cloud.githubusercontent.com/assets/873919/18614255/0102dbcc-7d94-11e6-850d-15f8d8a36169.png)

The code is from the end of this file https://github.com/vasily-kirichenko/haskell-book/blob/master/src/Applicatives.hs

**Comment by lierdakil** [comment]
You're basically hitting a limitation of Atom's grammar model, which is not entirely adequate for languages with significant whitespace. Long story short, scoped/inline types are limited to single line in grammar, and there's not much I can do about that.

**Comment by vasily-kirichenko** [comment]
OK, thanks.
