### ISSUE TITLE
Data Kinds: Promoted data constructor notation

### ISSUE THREAD

**Issue by deiga** [atom-haskell/language-haskell#91]
I'd love to be able to use the single-quote constructor notation of Data Kinds without having to remove a second single-quote every time. 

Do you think this would be possible to implement?

`Promoted data constructors can referred to in type signatures by prefixing them with a single quote` http://dev.stephendiehl.com/hask/#data-kinds

**Comment by lierdakil** [comment]
This functionality is handled by bracket-matcher package. You can disable bracket/quote matching either globally in package settings, or for Haskell files specifically with something like this in your config file:
```cson
".haskell.source":
  "bracket-matcher":
    autocompleteBrackets: false
```

Note that this will disable `()`, `[]` etc matching as well. There is no finer-grained control over package's behavior, sadly. Also see https://github.com/atom/bracket-matcher/issues/171

**Comment by lierdakil** [comment]
Also worth mentioning, there's a PR currently open that would allow for more fine-grained customization https://github.com/atom/bracket-matcher/pull/249
