### ISSUE TITLE
Type-level strings not supported

### ISSUE THREAD

**Issue by DimaSamoz** [atom-haskell/language-haskell#95]
Quite a niche feature, but it might be easy to fix.

The GHC.TypeLits package allows for type-level string literals, which are currently highlighted like types, constructors and operators:

![image](https://cloud.githubusercontent.com/assets/16826557/20330058/0bdc0a5e-ab94-11e6-9da2-bf065a977ac1.png)

Could be just a matter of making a rule for double quoted text after `::`?

Great package by the way, thank you for your work!

**Comment by lierdakil** [comment]
Well, I hope I didn't mess anything else up with this, but v1.10.1 supports type-level string literals. And yes, this was a matter of adding a rule for strings in type signature scope.

**Comment by DimaSamoz** [comment]
Amazing, thank you! 👍
