### ISSUE TITLE
String with a regex anchor and an escaped whitespace char

### ISSUE THREAD

**Issue by dcastro** [atom-haskell/language-haskell#96]
The highlighting seems to break when I type in a string with a regex "beginning" anchor (`^`) and an escaped whitespace character, e.g. `"^\\ "`.

![haskell-lang](https://cloud.githubusercontent.com/assets/718166/20351543/2f611ff6-ac0b-11e6-886a-533945ccdb6c.png)

**Comment by lierdakil** [comment]
Should be fixed in v1.10.1. Thanks for reporting!

This was due to flaky control character tokenization (i.e. `\^@` and similar)... nobody seemingly ran into this until now. Which I find strange, but oh well.

**Comment by dcastro** [comment]
Wow, thanks for the quick turnaround!

Yes, it's working now, appreciate it. Keep up the good work!
