### ISSUE TITLE
language-haskell only recognizes packages in Prelude.

### ISSUE THREAD

**Issue by miladz68** [atom-haskell/language-haskell#98]
in a .hs file when I write
`import Control.Monad.Random`

I get the following error:

> Could not find module ‘Control.Monad.Random’
Use -v to see a list of the files searched for.

please help !

**Comment by lierdakil** [comment]
language-haskell has no direct relation to this. Where do you get this error anyway? Why did you assume it's language-haskell's fault? I'm afraid I can't help you without more information.

**Comment by miladz68** [comment]
I guess it is ide-haksell's fault, sorry I bothered you.
